In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/2019_movie_rankings.csv', index_col = 'Position', encoding = "ISO-8859-1")

In [3]:
df

,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
Position,,,,,,,,,,,,,,
1,tt2584384,11/7/2019,11/7/2019,NaN,Jojo Rabbit,https://www.imdb.com/title/tt2584384/,movie,8.0,108,2019,"Comedy, Drama, War",75486,9/8/2019,Taika Waititi
2,tt1489887,5/27/2019,5/27/2019,NaN,Booksmart,https://www.imdb.com/title/tt1489887/,movie,7.2,102,2019,Comedy,62307,3/10/2019,Olivia Wilde
3,tt6751668,10/26/2019,10/26/2019,NaN,Gisaengchung,https://www.imdb.com/title/tt6751668/,movie,8.6,132,2019,"Comedy, Crime, Drama, Thriller",187097,5/21/2019,Bong Joon Ho
4,tt8079248,6/29/2019,6/29/2019,NaN,Yesterday,https://www.imdb.com/title/tt8079248/,movie,6.9,116,2019,"Comedy, Fantasy, Music, Musical, Romance",76435,5/4/2019,Danny Boyle
5,tt1979376,6/22/2019,6/22/2019,NaN,Toy Story 4,https://www.imdb.com/title/tt1979376/,movie,7.9,100,2019,"Animation, Adventure, Comedy, Family, Fantasy",150005,6/11/2019,Josh Cooley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,tt7329656,8/20/2019,8/20/2019,NaN,47 Meters Down: Uncaged,https://www.imdb.com/title/tt7329656/,movie,5.0,90,2019,"Adventure, Drama, Horror, Thriller",11466,8/15/2019,Johannes Roberts
139,tt10481868,12/13/2019,12/13/2019,NaN,Black Christmas,https://www.imdb.com/title/tt10481868/,movie,3.1,92,2019,"Horror, Mystery, Thriller",4516,12/11/2019,Sophia Takal
140,tt8179388,9/9/2019,9/9/2019,Not in theater.,Rim of the World,https://www.imdb.com/title/tt8179388/,movie,5.1,98,2019,"Action, Adventure, Comedy, Sci-Fi",15480,5/24/2019,McG
141,tt1206885,9/26/2019,9/26/2019,NaN,Rambo: Last Blood,https://www.imdb.com/title/tt1206885/,movie,6.2,89,2019,"Action, Adventure, Thriller",54397,9/18/2019,Adrian Grunberg
142,tt9134216,11/13/2019,11/13/2019,NaN,Playing with Fire,https://www.imdb.com/title/tt9134216/,movie,4.8,96,2019,"Comedy, Family",4380,11/7/2019,Andy Fickman

In [4]:
df.shape # atribute, without (), show us number of rows and columns

(142, 14)

In [5]:
df.info() # for more informations, this is method and must go with ()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142 entries, 1 to 142
Data columns (total 14 columns):
Const             142 non-null object
Created           142 non-null object
Modified          142 non-null object
Description       19 non-null object
Title             142 non-null object
URL               142 non-null object
Title Type        142 non-null object
IMDb Rating       142 non-null float64
Runtime (mins)    142 non-null int64
Year              142 non-null int64
Genres            142 non-null object
Num Votes         142 non-null int64
Release Date      142 non-null object
Directors         142 non-null object
dtypes: float64(1), int64(3), object(10)
memory usage: 16.6+ KB

In [6]:
df.head() # to see just first 5 rows

,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
Position,,,,,,,,,,,,,,
1,tt2584384,11/7/2019,11/7/2019,NaN,Jojo Rabbit,https://www.imdb.com/title/tt2584384/,movie,8.0,108,2019,"Comedy, Drama, War",75486,9/8/2019,Taika Waititi
2,tt1489887,5/27/2019,5/27/2019,NaN,Booksmart,https://www.imdb.com/title/tt1489887/,movie,7.2,102,2019,Comedy,62307,3/10/2019,Olivia Wilde
3,tt6751668,10/26/2019,10/26/2019,NaN,Gisaengchung,https://www.imdb.com/title/tt6751668/,movie,8.6,132,2019,"Comedy, Crime, Drama, Thriller",187097,5/21/2019,Bong Joon Ho
4,tt8079248,6/29/2019,6/29/2019,NaN,Yesterday,https://www.imdb.com/title/tt8079248/,movie,6.9,116,2019,"Comedy, Fantasy, Music, Musical, Romance",76435,5/4/2019,Danny Boyle
5,tt1979376,6/22/2019,6/22/2019,NaN,Toy Story 4,https://www.imdb.com/title/tt1979376/,movie,7.9,100,2019,"Animation, Adventure, Comedy, Family, Fantasy",150005,6/11/2019,Josh Cooley

In [7]:
df.tail(10) # to see just last 10 rows

,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
Position,,,,,,,,,,,,,,
133,tt7390646,10/25/2019,10/25/2019,NaN,Black and Blue,https://www.imdb.com/title/tt7390646/,movie,6.1,108,2019,"Action, Crime, Drama, Thriller",6737,9/21/2019,Deon Taylor
134,tt8323104,3/16/2019,3/16/2019,NaN,Nancy Drew and the Hidden Staircase,https://www.imdb.com/title/tt8323104/,movie,5.7,89,2019,"Comedy, Crime, Drama, Family, Mystery",2529,3/15/2019,Katt Shea
135,tt8085790,4/18/2019,4/18/2019,NaN,Little,https://www.imdb.com/title/tt8085790/,movie,5.4,109,2019,"Comedy, Fantasy, Romance",8187,4/11/2019,Tina Gordon
136,tt8695030,6/15/2019,6/15/2019,NaN,The Dead Don't Die,https://www.imdb.com/title/tt8695030/,movie,5.5,104,2019,"Comedy, Fantasy, Horror",35941,5/14/2019,Jim Jarmusch
137,tt4154916,1/13/2019,1/13/2019,NaN,Replicas,https://www.imdb.com/title/tt4154916/,movie,5.5,107,2018,"Drama, Sci-Fi, Thriller",25679,10/26/2018,Jeffrey Nachmanoff
138,tt7329656,8/20/2019,8/20/2019,NaN,47 Meters Down: Uncaged,https://www.imdb.com/title/tt7329656/,movie,5.0,90,2019,"Adventure, Drama, Horror, Thriller",11466,8/15/2019,Johannes Roberts
139,tt10481868,12/13/2019,12/13/2019,NaN,Black Christmas,https://www.imdb.com/title/tt10481868/,movie,3.1,92,2019,"Horror, Mystery, Thriller",4516,12/11/2019,Sophia Takal
140,tt8179388,9/9/2019,9/9/2019,Not in theater.,Rim of the World,https://www.imdb.com/title/tt8179388/,movie,5.1,98,2019,"Action, Adventure, Comedy, Sci-Fi",15480,5/24/2019,McG
141,tt1206885,9/26/2019,9/26/2019,NaN,Rambo: Last Blood,https://www.imdb.com/title/tt1206885/,movie,6.2,89,2019,"Action, Adventure, Thriller",54397,9/18/2019,Adrian Grunberg
142,tt9134216,11/13/2019,11/13/2019,NaN,Playing with Fire,https://www.imdb.com/title/tt9134216/,movie,4.8,96,2019,"Comedy, Family",4380,11/7/2019,Andy Fickman

In [8]:
df.columns # to see all columns

Index(['Const', 'Created', 'Modified', 'Description', 'Title', 'URL',
       'Title Type', 'IMDb Rating', 'Runtime (mins)', 'Year', 'Genres',
       'Num Votes', 'Release Date', 'Directors'],
      dtype='object')

In [9]:
df['Directors'] # to see just certain column, grab all responses, access like a key in dict

Position
1         Taika Waititi
2          Olivia Wilde
3          Bong Joon Ho
4           Danny Boyle
5           Josh Cooley
             ...
138    Johannes Roberts
139        Sophia Takal
140                 McG
141     Adrian Grunberg
142        Andy Fickman
Name: Directors, Length: 142, dtype: object

In [10]:
df['Directors'].value_counts() # how many responses with XXX

Frant Gwo                               1
Ang Lee                                 1
Noah Baumbach                           1
Carlos MartÃ­nez LÃ³pez, Sergio Pablos    1
James Gray                              1
                                       ..
Ry Russo-Young                          1
M. Night Shyamalan                      1
Josh Cooley                             1
Todd Douglas Miller                     1
RyÃ»suke Hamaguchi                       1
Name: Directors, Length: 142, dtype: int64

In [11]:
filt = df['Genres'].str.contains('Comedy') # grab genres

In [12]:
filt # show us only True or False

Position
1       True
2       True
3       True
4       True
5       True
       ...
138    False
139    False
140     True
141    False
142     True
Name: Genres, Length: 142, dtype: bool

In [13]:
comedy = df.loc[filt] # create mask for data, show us only cells with Comedy word

In [14]:
df.shape # atribute, without (), show us number of rows and columns

(142, 14)

In [15]:
comedy.shape # only comedy movie

(50, 14)

In [16]:
df['IMDb Rating'].value_counts()

6.9    11
7.5     8
6.6     7
6.2     7
6.3     7
5.8     7
6.8     7
7.7     6
7.0     6
6.5     5
7.6     5
6.0     5
6.1     5
7.2     4
6.7     4
7.8     3
5.9     3
5.5     3
8.2     3
7.9     3
5.7     3
8.0     3
7.1     2
5.0     2
8.5     2
7.4     2
5.6     2
6.4     2
8.6     2
8.1     2
7.3     2
5.4     2
2.8     1
5.1     1
5.2     1
3.1     1
5.3     1
4.8     1
4.2     1
Name: IMDb Rating, dtype: int64

In [17]:
# Write it to a csv, just comedy movies
comedy.to_csv('data/2019_movie_rankings_comedy.csv', header=True, index=True)

In [18]:
high_rating = (comedy['IMDb Rating'] > 8.0) # filter comedy movies with rating higher than 8.0

In [19]:
high_rating = comedy.loc[high_rating]

In [20]:
high_rating.sort_values(by=['IMDb Rating'], ascending=False) # sort by IMDb rating

,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
Position,,,,,,,,,,,,,,
3,tt6751668,10/26/2019,10/26/2019,NaN,Gisaengchung,https://www.imdb.com/title/tt6751668/,movie,8.6,132,2019,"Comedy, Crime, Drama, Thriller",187097,5/21/2019,Bong Joon Ho
6,tt4729430,12/2/2019,12/2/2019,Not in theater.,Klaus,https://www.imdb.com/title/tt4729430/,movie,8.2,96,2019,"Animation, Adventure, Comedy, Family",53252,11/8/2019,"Carlos MartÃ­nez LÃ³pez, Sergio Pablos"
11,tt7653254,12/11/2019,12/11/2019,Not in theater.,Marriage Story,https://www.imdb.com/title/tt7653254/,movie,8.1,137,2019,"Comedy, Drama, Romance",151624,8/29/2019,Noah Baumbach

In [21]:
high_rating.shape # only comedy movie with high rating

(3, 14)

In [22]:
# Write it to a csv, just comedy movies with rating higher than 8.0
high_rating.to_csv('data/2019_movie_rankings_comedy_best.csv', header=True, index=True)